export const LOAD = 'RECIPES/LOAD';
export const LOAD_RECIPES_SUCCESS = 'RECIPES/LOAD_SUCCESS';
export const LOAD_RECIPE_SUCCESS = 'RECIPES/LOAD_RECIPE_SUCCESS';
export const LOAD_RECIPES_FAILURE = 'RECIPES/LOAD_FAILURE';
export const REFRESH = 'RECIPES/REFRESH_RECIPES';
